### ISSUE TITLE
Skipped error when rule is not registred

### ISSUE THREAD

**Issue by DanielHreben** [Prots/olifer#1]
http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20user_name%3A%20%5C%22not_registred_rule%5C%22%5Cn%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20user_name%3A%20%5C%22%3BDROP%20DATABASE%20users%3B%5C%22%5Cn%7D%22%7D

**Comment by Prots** [comment]
Fixed, thanks!
