### ISSUE TITLE
if you try to put a default object, the application generates an error "FORMAT ERROR"

### ISSUE THREAD

**Issue by vkletsko** [Prots/olifer#5]
i mean this case
my rule >>
{
      "action": ["required", {"max_length":30}],
      "some_obj": [{ 
        "default":{},
        "list_of_objects": {
          "name": ["required",{"max_length":50}],
          "value": ["required",{"max_length":300}]
        }
      }]
    }
result should be >>
{
    "action": "get",
    "templateParams": {}
}

**Comment by Prots** [comment]
Fixed, tests was passed.

**Comment by vkletsko** [comment]
thanks a lot ;)
