### ISSUE TITLE
The rule list_of doesn't work

### ISSUE THREAD

**Issue by maximilyin** [Prots/olifer#6]
Description the rule list_of:

Allows you to describe validation rules for a list. Validation rules will be applyed for each array element.

Error code: depends on nested validators

Example:

// new syntax (introduced in v0.4)
{ product_ids: { 'list_of': 'positive_integer' }}
{ product_ids: { 'list_of': ['required',  'positive_integer'] }} // new syntax

Please fix this functionality. Best regards!

**Comment by Prots** [comment]
Could you please show particular example from your application?

**Comment by maximilyin** [comment]
Sorry, I was inattentive. This rule works!
